### ISSUE TITLE
DHT22 reset if timing fails

### ISSUE THREAD

**Issue by gulbrillo** [Tobi0892/octoprint-mqtt-enclosure#1]
I started looking into the MQTT OctoDash integration for your DHT22 sensor readout. However, I cannot find the part in your code where VCC is set to GPIO 17 if timing fails. Did you get rid of that part? It looks like you are now driving the DHT22s with power from different GPIOs and switch them off when you are done reading the data?
If you are down, I'd love to chat with you for a few minutes to understand your code. :)

**Comment by Tobi0892** [comment]
@gulbrillo

Yes, I used an 2n2222 transistor / resistor combination in order to power all DHT22 via 3,3 / 5V and being able to control the power via one GPIO. However, it turned out that I can reach with this combination only 2,6 volts which is too low for the sensors.

As the pi has 20+ freely usable GPIOs I decided to control each DHT22 individually. I pushed another commit six days ago where I changed the read method of the DHT22 class to accept the data and power pin as argument:
``  def read(self, data, power): `` 
Thus:
`` MQTT_message["filament3"] = DHT22.read(5, 6) `` 

With this you can run 10+ DHT22 sensors with individual power and data lines or decide to share power (connect more than one DHT22 to a GPIO) to connect even more.

As the DHT22s are not powered constantly but just receive power during each reading cycle, I observed no reading failures due to timing. Its like a reset for every cycle.

Nevertheless, all DHT22 share a common ground.

**Comment by Tobi0892** [comment]
@gulbrillo  Discord: Tobi0892#1783
